ERP.WEB/Controllers/SettingsController.cs
using System;
using System.Web;
using System.Web.Mvc;
using ERP.DAL.Model;
using ERP.INFRASTRUCTURE;
using ERP.INFRASTRUCTURE.Global;
using ERP.REPOSITORIES.Helper;
using ERP.REPOSITORIES.IRepositories;
using Party = ERP.INFRASTRUCTURE.Party;
using Employee = ERP.INFRASTRUCTURE.Employee;

namespace ERP.WEB.Controllers
{
    public class SettingsController : Controller
    {
        #region Settings Setup

        private const string SaveEmployeePartial = "Partial/_SaveEmployee";
        private const string SavePartyPartial = "Partial/_SaveParty";
        private const string SaveBankPartial = "Partial/_SaveBank";
        private const string SaveAreaPartial = "Partial/_SaveArea";
        private DbResponse _dbResponse;
        private readonly LogInInfo _logInInfo;
        private readonly ERPEntities _dbEntities;

        private readonly IPartyManager _partyManager;
        private readonly IEmployeeManager _employeeManager;
        private readonly ILedgerGroupManager _transactionHeaderManager;

        #endregion
        public SettingsController(IPartyManager partyManager, IEmployeeManager employeeManager, HttpContext httpContext, DbResponse dbResponse, LogInInfo logInInfo, ERPEntities dbEntities, ILedgerGroupManager transactionHeaderManager)
        {
            _dbResponse = dbResponse;
            _dbEntities = dbEntities;
            _partyManager = partyManager;
            _employeeManager = employeeManager;
            _transactionHeaderManager = transactionHeaderManager;
            var httpContext1 = httpContext;
            if (httpContext1.Request.RequestContext.HttpContext.Session != null)
                _logInInfo = httpContext1.Request.RequestContext.HttpContext.Session["loginInfo"] as LogInInfo;
            else
            {
                _logInInfo = null;
            }
        }
        #region Employee
        public ActionResult EmployeeList()
        {
            ViewBag.EmployeeList = _employeeManager.GetEmployees();
            return View();
        }
        [HttpGet]
        public ActionResult SaveEmployee(string param)
        {
            //if (param == Constants.EmptyString)
            //{
            //    return PartialView(SaveEmployeePartial, new Employee { DateOfJoining = DateTime.Today });
            //}
            //var obj = _employeeManager.GetEmployee(Convert.ToInt64(param));
            //obj.IsEdit = true; //** obj.IsEdit 
            //return PartialView(SaveEmployeePartial, obj);
            return null;
        }

        [HttpPost]
        public JsonResult SaveEmployee(Employee obj)
        {
            // addEmployee also work for update or edit.. by sabbir
            var response = _employeeManager.AddEmployee(obj, _logInInfo);
            return Json(response, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult DeleteEmployee(long id)
        {
            var response = _employeeManager.DeleteEmployee(id, _logInInfo);
            return Json(response, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region  Party
        public ActionResult SupplierPartyList()
        {
            ViewBag.PartyType = PropertyConstants.Supplier;
            ViewBag.PartyList = _partyManager.GetPartiesByType((int)Constants.PartyType.SupplierParty);
            return View("PartyList");
        }
        public ActionResult DealerPartyList()
        {
            ViewBag.PartyType = PropertyConstants.Dealer;
            ViewBag.PartyList = _partyManager.GetPartiesByType((int)Constants.PartyType.DealerParty);
            return View("PartyList");
        }
        [HttpGet]
        public ActionResult SaveParty(string param)
        {
            // param contain "-1^1" or "-1^2" or <any id>^partyType
            var paramList = param.Split('^');
            ViewBag.partyType = paramList[1] == PropertyConstants.Supplier.ToString() ? "Supplier" : "Client";

            if (paramList[0] == Constants.EmptyString)
            {
                return PartialView(SavePartyPartial, new LedgerViewModel { PropertyId = Convert.ToInt32(paramList[1]) });
            }
            var obj = _partyManager.GetParty(Convert.ToInt64(paramList[0]));
            obj.PropertyId = Convert.ToInt32(obj.PropertyId);
            return PartialView(SavePartyPartial, obj);
        }

        [HttpPost]
        public JsonResult SaveParty(LedgerViewModel obj)
        {
            var response = _partyManager.AddParty(obj, _logInInfo);
            return Json(response, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult DeleteParty(string id)
        {
            long partyId;
            long.TryParse(id, out partyId);
            var response = _partyManager.DeleteParty(partyId, _logInInfo);
            return Json(response, JsonRequestBehavior.AllowGet);
        }
        #endregion

    }
}

ERP.WEB/Views/Accounting/LedgerGroupList.cshtml
@model IEnumerable<ERP.INFRASTRUCTURE.LedgerGroupViewModel>

@{
    ViewBag.Title = "Header List";
}
<div class="panel-heading">
    <h3 class="panel-title"><i class="fa fa-archive"></i> Header List</h3>
    <div class="btn-add-partial">
            <a href="@Url.Action("SaveLedgerGroup", "Accounting")" class="btn btn-default">
                Create Header
            </a>
        </div>
</div>
<div class="panel-body minHeight">
    <div class="row">
        <div class="col-sm-12">
            <div class="panel panel-default">
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-hover dataTables">
                            <thead>
                                <tr>
                                    <th>Header Name</th>
                                    <th>Type </th>
                                    <th>Desc</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (Model != null)
                                {
                                    foreach (var item in Model)
                                    {

                                        <tr>
                                            <td><a href="@Url.Action("SaveLedgerGroup", new { id = item.Id })">@Html.DisplayFor(modelItem => item.Name)</a></td>
                                            <td>@Html.DisplayFor(modelItem => item.GroupName)</td>
                                            <td>@Html.DisplayFor(modelItem => item.Description)</td>
                                            <td>
                                                <abbr title="Edit"><a href="@Url.Action("SaveLedgerGroup", new { id = item.Id })" class="btn btn-default" title="Edit"><i class="fa fa-pencil fa-fw"></i>Edit</a></abbr>
                                                <abbr title="Delete"><button onclick="ConfirmDelete(@item.Id,'DeleteLedgerGroup')" class="btn btn-default editBM" title="Delete"><i class="fa fa-times"></i></button></abbr>
                                            </td>
                                        </tr>
                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                    <!-- /.table-responsive -->
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-sm-12 -->
    </div>
    <!-- /.row -->
</div>

@section scripts{
    @*<script src="~/Scripts/jquery.validate.min.js"></script>*@
    <script>

        $(function () {
            $('.dataTables').dataTable();
        });

        $('#addTSH').on("click", function (e) {

            $('.PartialModalContainer').load(this.href, function () {
                //$('.PartialModal').modal({
                //    keyboard: true
                //}, 'show');  .modal('show');
                $('.PartialModal').modal('show');

            });

            return false;

        });
        $('.editSH').on("click", function (e) {
            //alert();
            console.log(this.href);
            $('.PartialModalContainer').load(this.href, function () {
                $('.PartialModal').modal({
                    keyboard: true
                }, 'show');

            });
            $(function () {
                $('.datepicker').datepicker({ autoclose: true, todayHighlight: true }).on('changeDate', function (e) {
                    $(this).datepicker('hide');
                });
            });
            return false;
        });

        $(document).on('click', '#closeModal', function () {
            window.location.replace('@Url.Action("LedgerGroupList","Settings")');
        });
    </script>
}

ERP.WEB/Views/Accounting/LedgerList.cshtml
@model IEnumerable<ERP.INFRASTRUCTURE.LedgerViewModel>

@{
    ViewBag.Title = "Transaction Header List";
}
<div class="panel-heading">
    <h3 class="panel-title"><i class="fa fa-archive"></i> Account Ledgers</h3>
    <div class="btn-add-partial">
        <a href="@Url.Action("SaveLedger", "Accounting")" class="btn btn-default">
            Create Ledger
        </a>
    </div>
</div>

<div class="panel-body minHeight">
    <div class="row">
        <div class="col-sm-12">
            <div class="panel panel-default">
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-hover dataTables">
                            <thead>
                                <tr>
                                    <th>Account Name</th>
                                    <th>Under Header</th>
                                    <th>Desc</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (Model != null)
                                {
                                    foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>
                                                <a href="@Url.Action("SaveLedger", new { id = item.Id })">@Html.DisplayFor(modelItem => item.Name)</a>
                                            </td>
                                            <td>@Html.DisplayFor(modelItem => item.GroupName)</td>
                                            <td>@Html.DisplayFor(modelItem => item.Description)</td>
                                            <td>
                                                <abbr title="Delete"><button class="btn btn-default " onclick="ConfirmDelete(@item.Id,'DeleteLedger')"> <i class="fa fa-trash-o fa-fw"></i></button></abbr>
                                            </td>
                                        </tr>
                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                    <!-- /.table-responsive -->
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-sm-12 -->
    </div>
    <!-- /.row -->
</div>

@section scripts{
    @*<script src="~/Scripts/jquery.validate.min.js"></script>*@
    <script>

        $(function () {
            $('.dataTables').dataTable();
        });

        $(document).on('click', '#closeModal', function () {
            window.location.replace('@Url.Action("LedgerGroupList","Settings")');
        });
    </script>
}

ERP.WEB/Views/Accounting/SaveLedger.cshtml
@model ERP.INFRASTRUCTURE.LedgerViewModel
<script>
    var formControl = {
        'IsSingle': true,
        'ControlStr': 'param<prop>Id^Name^LedgerGroupId^Description'
    };
    var formValidate = { 'IsChecked': false, 'validateStr': "" };
    var formUrl = "SaveLedger";
    var redirectUrl = "/Accounting/LedgerList";
    var messageType = "notification";
</script>
<div class="row" style="margin-top: 20px;">
    <div class="col-sm-2"></div>
    <div class="col-sm-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                Create Ledger Accounts
            </div>
            <div class="panel-body param">
                <div class="form-horizontal">
                    <div class="addclass"></div>
                    @Html.HiddenFor(model => model.IsEdit)
                    @Html.HiddenFor(model => model.Id)
                    @Html.ValidationSummary(true)
                    <div class="row">
                        <div class="control-label col-sm-3">@Html.DisplayNameFor(x => x.Name)</div>
                        <div class="col-sm-9">
                            @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
                            @Html.ValidationMessageFor(x => x.Name)
                        </div>
                    </div>
                    <div class="row">
                        <div class="control-label col-sm-3">Under Header</div>
                        <div class="col-sm-9">@Html.DropDownList("LedgerGroupId", new SelectList(ViewBag.ParentList, "Value", "Text"), new { @class = "form-control select", @id = "LedgerGroupId" })  </div>
                        @Html.ValidationMessageFor(x => x.LedgerGroupId)
                    </div>
                    <div class="row">
                        <div class="control-label col-sm-3">@Html.DisplayNameFor(x => x.Description)</div>
                        <div class="col-sm-9">
                            @Html.TextAreaFor(x => x.Description, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-offset-4 col-md-10">
                            <button id="save" class="btn btn-primary" onclick="thirdPartySubmitter(formControl, formValidate, formUrl, redirectUrl, messageType)">Save</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


@section scripts
{
    <script>
        $(document).ready(function () {
            $('.select').select2();

        });
        @*if ('@Model.IsEdit' == 'True') {
            $('#save').css('display', 'none');
        }*@

    </script>
}

ERP.WEB/Views/Accounting/SaveLedgerGroup.cshtml
@model ERP.INFRASTRUCTURE.LedgerGroupViewModel
           
<script>
    var formControl = {
        'IsSingle': true,
        'ControlStr': 'param<prop>Id^Name^GroupHeaderId^Description'
    };
    var formValidate = { 'IsChecked': false, 'validateStr': "" };
    var formUrl = "SaveLedgerGroup";
    var redirectUrl = "/Accounting/LedgerGroupList";
    var messageType = "notification";
</script>
<div class="row" style="margin-top: 20px;">
    <div class="col-sm-2"></div>
    <div class="col-sm-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                Create Header
            </div>
            <div class="panel-body param">
                <div class="form-horizontal">
                    <div class="addclass"></div>
                    @Html.HiddenFor(model => model.IsEdit)
                    @Html.HiddenFor(model => model.Id)
                    @Html.ValidationSummary(true)
                    <div class="row">
                        <div class="control-label col-sm-3">@Html.DisplayNameFor(x => x.Name)</div>
                        <div class="col-sm-9">
                            @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
                            @Html.ValidationMessageFor(x => x.Name)
                        </div>
                    </div>
                    <div class="row">
                        <div class="control-label col-sm-3">Header Type</div>
                        <div class="col-sm-9">@Html.DropDownListFor(x => x.GroupHeaderId, new SelectList(ViewBag.ParentList, "Value", "Text"), new { @class = "form-control" })  </div>
                        @Html.ValidationMessageFor(x => x.GroupHeaderId)
                    </div>
                    <div class="row">
                        <div class="control-label col-sm-3">@Html.DisplayNameFor(x => x.Description)</div>
                        <div class="col-sm-9">
                            @Html.TextAreaFor(x => x.Description, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-offset-4 col-md-10">
                            <button id="save" class="btn btn-primary" onclick="thirdPartySubmitter(formControl, formValidate, formUrl, redirectUrl, messageType)">Save</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts
{
    <script>
        @*if ('@Model.IsEdit' == 'True') {
            $('#save').css('display', 'none');
        }*@

    </script>
}